# Generated by Django 5.1.4 on 2026-09-18 12:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(help_text='Processing area bounding box', srid=4326)),
                ('job_type', models.CharField(choices=[('fire_detection', 'Fire Detection'), ('burn_mapping', 'Burn Severity Mapping')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('params', models.JSONField(default=dict, help_text='Job parameters')),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BurnArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(db_index=True, srid=4326)),
                ('area_ha', models.FloatField(help_text='Burned area in hectares')),
                ('severity', models.CharField(choices=[('unburned', 'Unburned'), ('low', 'Low severity'), ('moderate', 'Moderate severity'), ('high', 'High severity')], db_index=True, max_length=20)),
                ('dnbr_mean', models.FloatField(blank=True, help_text='Mean dNBR value', null=True)),
                ('pre_date', models.DateField(help_text='Pre-fire image date')),
                ('post_date', models.DateField(help_text='Post-fire image date')),
                ('satellite', models.CharField(default='Sentinel-2', max_length=30)),
                ('tile_id', models.CharField(blank=True, help_text='Sentinel-2 tile ID', max_length=20)),
                ('processing_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pre_date'],
                'indexes': [models.Index(fields=['severity', 'pre_date'], name='fires_burna_severit_022ebe_idx')],
            },
        ),
        migrations.CreateModel(
            name='FireHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
                ('brightness', models.FloatField(help_text='Brightness temperature in Kelvin')),
                ('brightness_31', models.FloatField(blank=True, help_text='3.1µm brightness temperature (MODIS only)', null=True)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('nominal', 'Nominal'), ('high', 'High')], default='nominal', max_length=10)),
                ('frp', models.FloatField(blank=True, help_text='Fire Radiative Power in MW', null=True)),
                ('source', models.CharField(choices=[('VIIRS_SNPP', 'VIIRS Suomi NPP'), ('VIIRS_NOAA20', 'VIIRS NOAA-20'), ('MODIS_Aqua', 'MODIS Aqua'), ('MODIS_Terra', 'MODIS Terra')], db_index=True, max_length=20)),
                ('satellite', models.CharField(blank=True, max_length=20)),
                ('instrument', models.CharField(blank=True, max_length=20)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('daynight', models.CharField(default='D', help_text='D=Day, N=Night', max_length=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('filter_flag', models.CharField(blank=True, help_text='Reason if filtered out (e.g., industrial, reflection)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['source', 'detected_at'], name='fires_fireh_source_ac4a30_idx'), models.Index(fields=['confidence'], name='fires_fireh_confide_ecab77_idx')],
            },
        ),
    ]
