# Generated by Django 5.1.4 on 2026-09-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burnarea',
            name='tile_id',
            field=models.CharField(blank=True, help_text='Sentinel-2 tile ID', max_length=100),
        ),
    ]
