# Generated by Django 5.1.4 on 2026-09-19 07:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0002_alter_burnarea_tile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('query_params', models.JSONField(help_text='Query parameters (bbox, dates)')),
                ('summary', models.JSONField(help_text='Summary statistics')),
                ('severity_distribution', models.JSONField(help_text='Breakdown by severity class')),
                ('by_landcover', models.JSONField(blank=True, help_text='Breakdown by land cover type', null=True)),
                ('data_quality', models.JSONField(blank=True, help_text='Data quality metrics', null=True)),
                ('burn_areas', models.ManyToManyField(blank=True, related_name='reports', to='fires.burnarea')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='IndustrialZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(db_index=True, srid=4326)),
                ('zone_type', models.CharField(choices=[('industrial', 'Industrial'), ('oil_and_gas', 'Oil & Gas'), ('power_plant', 'Power Plant'), ('quarry', 'Quarry'), ('mine', 'Mine'), ('factory', 'Factory'), ('warehouse', 'Warehouse')], db_index=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(default='overture_maps', max_length=50)),
                ('source_id', models.CharField(blank=True, db_index=True, help_text='ID from source dataset', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['zone_type', 'source'], name='fires_indus_zone_ty_a7e129_idx')],
            },
        ),
    ]
